### ISSUE TITLE
Required version of symfony/property-access

### ISSUE THREAD

**Issue by Ace-COM** [answear/luigis-box-bundle#36]
Hello guys,

I was willing to give this a try, but I have a problem with dependecies, resp. with "symfony/property-access": "^4.1" because my project has version 5.2.4 locked and thus composer cannot install this library.

would it be a big problem to update the dependency to support ^5.2 ?

I ran PHPUnit tests on updated dependency and all seemd to pass

**Comment by malarzm** [comment]
@Ace-COM we'd love to allow `4.x || 5.x` for all Symfony packages we're using. If you have some time please feel free to send us a PR with updated composer.json, tests will tell us truth whether everything is still working fine :)

**Comment by Ace-COM** [comment]
I am not really used to git (used svn more - perhaps I am just too old :D ).. I created PR, but it seems it was pushed directly as commit to your code? If I did something obviously wrong, please let me know :)

**Comment by Ace-COM** [comment]
Please give it a try

**Comment by lukasz-falda** [comment]
Merged and tagged as v2.3.0
https://github.com/answear/luigis-box-bundle/releases/tag/v2.3.0
