### ISSUE TITLE
php-http/guzzle7-adapter ?

### ISSUE THREAD

**Issue by Ace-COM** [answear/luigis-box-bundle#38]
Hello guys,

can I propose a switch from _php-http/guzzle6-adapter_ to _php-http/guzzle7-adapter_ ?

I am not sure whether your project allows the change, but we are using guzzle7 in our project and the client should be backward compatible. Would it be possible to update the dependencies (if your projects allows it) or should I publish my own package with updated dependecies in order to make it work for me?

I can create another pull request if it is OK for you

**Comment by Ace-COM** [comment]
Of course, if it is not possible, then I'd be happy for your agreement to use your library as a base for my completely separate implementation where I would perhaps go directly for Guzzle 7 as it does support PSR-18 natively...

**Comment by lukasz-falda** [comment]
please, give us some time. I need to check it out.

**Comment by Ace-COM** [comment]
Sure. Let me know what you found out :) Thank you...

**Comment by lukasz-falda** [comment]
v2.4.0 version should meet your needs

**Comment by Ace-COM** [comment]
Awsome, thank you very much :)
