### ISSUE TITLE
Nested field for ContentUpdate

### ISSUE THREAD

**Issue by janco-naninails** [answear/luigis-box-bundle#40]
Hello guys, 

it seems your library does not support **nested** field in contentUpdate functionality (see [https://live.luigisbox.com/#content-updates-content-update](https://live.luigisbox.com/#content-updates-content-update)).

Would it be possible to quickly add this to your code, so that I can continue using your library for my project? Otherwise I would have to make my own implementation, which would take much more time :(

**Comment by lukasz-falda** [comment]
Hi,

we have `\Answear\LuigisBoxBundle\ValueObject\AbstractContentUpdate::$nested` field.
Maybe this is what you need.

**Comment by janco-naninails** [comment]
Oh, OK... so I see you have a setter for that. I expected it to be directly in constructor. Looks good, I will give it a try and let you know the outcome. Otherwise if I do not come back in a week, then you may close this one ;)

Thank you for your swift support.

**Comment by janco-naninails** [comment]
Awsome... worked like charm. Thank you very much.
