### ISSUE TITLE
What triggers BadRequest Exception?

### ISSUE THREAD

**Issue by janco-naninails** [answear/luigis-box-bundle#42]
Hello guys,
I am trying to find out why am I sometimes getting BadRequest Exception when trying to use PartialUpdate. For me it seems like perhaps the item is missing in the Luigi's Box catalogue, but I cannot pinpoint the real cause because it is only triggered when I send more than one item per request (10 or more up to 50).

What is the real cause? How can I find out and get the real response from the Lugi's Box API so that I can take a look at which request failed and why?

**Comment by lukasz-falda** [comment]
Hi,

`\Answear\LuigisBoxBundle\Exception\BadRequestException` has method `getResponse()` so you can catch this exception and get real response from it.

**Comment by janco-naninails** [comment]
Thank you, I just figured it out this morning. I am closing this ticket.
