### ISSUE TITLE
Dynamic key configuration

### ISSUE THREAD

**Issue by cuchac** [answear/luigis-box-bundle#45]
Hello,

we need to allow users of our application to define at least `publicKey` and `privateKey` in settings. We can not hard-code them to `config.yml`.

I did not find any correct way to do this. Always some private members/methods were blocking the way.

Will you accept some PR to allow this dynamic setting? Will you give me some hint how you would implement that, so that I can implement this functionality in the way you like?

**Comment by lukasz-falda** [comment]
Yes sure, try add public
`ConfigProvider::addConfig` method
```
public function addConfig(string $configName, ConfigDTO $configDTO):void
```

We'll see in PR what will come of it 😄
